"""Turn a TrueType font into an Adafruit GFX font header.

The head draws its notices itself, for when it cannot show a page, and this
lets it write in the same face as the pages the server renders. A GFX font is
one bit deep: the glyphs are rendered by FreeType's monochrome rasteriser,
the way Adafruit's own fontconvert renders them, not thresholded from
antialiased ones.

Variable fonts take their axes as options, so an instance matches the CSS
that sets it. Tracking bakes letter-spacing into each glyph's advance, since
GFX text has none of its own.

    python scripts/gfxfont.py server/static/fonts/Fraunces.ttf 26 \\
        --name FrauncesDetail --weight 400 --soft 40 > include/head/fonts/FrauncesDetail.h

Needs Pillow; server/.venv has it.
"""
from __future__ import annotations

import argparse
import sys

from PIL import Image, ImageDraw, ImageFont

# The axes this knows by name, and the option that sets each.
AXES = {"Optical Size": "opsz", "Weight": "weight", "Softness": "soft", "Wonky": "wonky"}


def load(path: str, size: int, settings: dict) -> ImageFont.FreeTypeFont:
    font = ImageFont.truetype(path, size)
    try:
        axes = font.get_variation_axes()
    except OSError:
        return font   # a static font: nothing to set
    values = []
    for axis in axes:
        name = axis["name"].decode() if isinstance(axis["name"], bytes) else axis["name"]
        key = AXES.get(name)
        # CSS sets the optical size to the font size unless told otherwise.
        wanted = settings.get(key) if key else None
        if key == "opsz" and wanted is None:
            wanted = size
        values.append(axis["default"] if wanted is None else wanted)
    font.set_variation_by_axes(values)
    return font


def glyph(font: ImageFont.FreeTypeFont, ch: str, tracking: int):
    """One glyph's packed bits and its GFX metrics, relative to the baseline."""
    advance = round(font.getlength(ch, mode="1")) + tracking
    x0, y0, x1, y1 = font.getbbox(ch, mode="1", anchor="ls")
    w, h = max(0, x1 - x0), max(0, y1 - y0)
    if w == 0 or h == 0:
        return b"", 0, 0, advance, 0, 0
    img = Image.new("1", (w, h), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"
    draw.text((-x0, -y0), ch, font=font, fill=1, anchor="ls")
    # GFX packs a glyph's bits row after row with no row padding, most
    # significant bit first, and pads only the glyph's last byte.
    bits = [1 if img.getpixel((x, y)) else 0 for y in range(h) for x in range(w)]
    packed = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j, bit in enumerate(bits[i:i + 8]):
            byte |= bit << (7 - j)
        packed.append(byte)
    return bytes(packed), w, h, advance, x0, y0


def convert(path, size, name, first, last, tracking_em, settings) -> str:
    font = load(path, size, settings)
    tracking = round(tracking_em * size)
    ascent, descent = font.getmetrics()
    bitmap = bytearray()
    rows = []
    for code in range(first, last + 1):
        bits, w, h, adv, xo, yo = glyph(font, chr(code), tracking)
        for value, lo, hi, what in ((w, 0, 255, "width"), (h, 0, 255, "height"),
                                    (adv, 0, 255, "advance"), (xo, -128, 127, "x offset"),
                                    (yo, -128, 127, "y offset")):
            if not lo <= value <= hi:
                sys.exit(f"{chr(code)!r}: {what} {value} does not fit a GFX glyph")
        rows.append((len(bitmap), w, h, adv, xo, yo, code))
        bitmap += bits
    if len(bitmap) > 0xFFFF:
        sys.exit(f"{len(bitmap)} bytes of glyphs is more than a GFX font can index")

    out = [f"// {name}: generated by scripts/gfxfont.py from {path.split('/')[-1]}, {size} px,",
           f"// {' '.join(f'{k} {v}' for k, v in settings.items() if v is not None) or 'default axes'}"
           + (f", tracking {tracking_em} em" if tracking_em else "") + ".",
           "// SIL Open Font License 1.1; see OFL.txt beside this file. Do not edit by hand.",
           "#pragma once",
           "#include <Inkplate.h>   // GFXfont and GFXglyph",
           "",
           f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(bitmap), 12):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 12]) + ",")
    out.append("};")
    out.append("")
    out.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for off, w, h, adv, xo, yo, code in rows:
        shown = chr(code) if chr(code) not in "\\'" else "\\" + chr(code)
        out.append(f"  {{{off:5d}, {w:3d}, {h:3d}, {adv:3d}, {xo:4d}, {yo:4d}}},   // '{shown}'")
    out.append("};")
    out.append("")
    out.append(f"const GFXfont {name} PROGMEM = {{(uint8_t*){name}Bitmaps, (GFXglyph*){name}Glyphs,")
    out.append(f"                                0x{first:02X}, 0x{last:02X}, {ascent + descent}}};")
    return "\n".join(out) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("font")
    p.add_argument("size", type=int, help="pixels, as CSS px on a 1280-wide page")
    p.add_argument("--name", required=True)
    p.add_argument("--weight", type=float)
    p.add_argument("--soft", type=float)
    p.add_argument("--wonky", type=float)
    p.add_argument("--opsz", type=float, help="optical size; defaults to the pixel size, as CSS does")
    p.add_argument("--tracking", type=float, default=0.0, help="letter-spacing, in em")
    p.add_argument("--first", type=lambda s: int(s, 0), default=0x20)
    p.add_argument("--last", type=lambda s: int(s, 0), default=0x7E)
    a = p.parse_args()
    settings = {"weight": a.weight, "soft": a.soft, "wonky": a.wonky, "opsz": a.opsz}
    sys.stdout.write(convert(a.font, a.size, a.name, a.first, a.last, a.tracking, settings))


if __name__ == "__main__":
    main()
